# SPDX-License-Identifier: MIT

name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"

      - run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
